# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-31 12:28
from __future__ import unicode_literals

from django.db import migrations


def insert_read_types(apps, schema_editor):
    """
    Insert Read Types to prevent data import errors for new users
    : param apps:
    : param schema_editor:
    : return:
    """

    read_types = [
        'GSheet Import',
        'ONA', 'JSON',
        'Google Spreadsheet',
        'OneDrive',
        'CSV'
    ]

    ReadType = apps.get_model('silo', 'ReadType')
    for type in read_types:
        new_type = ReadType(read_type=type)
        new_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_read_types)
    ]
