# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(default=b'Germany', max_length=100)),
                ('email', models.CharField(default=b'user@hikaya.io', max_length=100)),
            ],
        ),
    ]
